In [12]:
from pulp import *
import pulp
import numpy as np
from grid_solve import solve_lp, solve_random_lp



In [13]:
size = 20
vehicle_start = np.array([[0,0]])
vehicle_end = np.array([[size, size]])
charger_loc = np.array([[10,10], [5, 5], [90, 90]])
charger_co2s = np.array([0.1, 0.2, 0.3])
start_battery = [30]
ending_battery = [10]
T = 30
prob, objective, x_out, c_out, b_out, c_cond_out, starts, ends =  solve_lp(T, vehicle_start, vehicle_end, charger_loc, charger_co2s, start_battery, ending_battery, speed=10, num_chargers_per_station=5, max_rate_of_charge=3, battery_per_mile=1, grid_size=size)
prob.status

Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/akshgarg/opt/anaconda3/envs/ML/lib/python3.7/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/ld/prbck6fj4tn7tt5rq173lfj40000gp/T/a45dfe3ae9a542f5bd6ff99f4abb5da6-pulp.mps timeMode elapsed branch printingOptions all solution /var/folders/ld/prbck6fj4tn7tt5rq173lfj40000gp/T/a45dfe3ae9a542f5bd6ff99f4abb5da6-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 331 COLUMNS
At line 1766 RHS
At line 2093 BOUNDS
At line 2329 ENDATA
Problem MODEL has 326 rows, 235 columns and 819 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 118 - 0.00 seconds
Cgl0004I processed model has 167 rows, 168 columns (168 integer (0 of which binary)) and 530 elements
Cutoff increment increased from 1e-05 to 0.0999
Cbc0012I Integer solution of 118 found by DiveCoefficient after 0 iterations and 0 nodes (0.01 se

1

In [9]:
x_out

array([[[ 0.,  0.],
        [ 0., 10.],
        [10., 10.],
        [15., 14.],
        [15., 17.],
        [18., 17.],
        [18., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.],
        [20., 20.]]])

In [10]:
b_out

array([[30., 23., 16., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
        10., 10., 10., 10.]])

In [11]:
c_out

array([[[3., 3., 3., 3., 3., 3., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [6]:
c_cond_out

array([[[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
         nan, nan, nan, nan, nan]]])